/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTeachRouteImport } from './routes/api/teach'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedSpoudeLibraryRouteImport } from './routes/_authenticated/spoude-library'
import { Route as AuthenticatedSpoudeRouteImport } from './routes/_authenticated/spoude'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSetsIdRouteImport } from './routes/_authenticated/sets.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeachRoute = ApiTeachRouteImport.update({
  id: '/api/teach',
  path: '/api/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpoudeLibraryRoute =
  AuthenticatedSpoudeLibraryRouteImport.update({
    id: '/spoude-library',
    path: '/spoude-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpoudeRoute = AuthenticatedSpoudeRouteImport.update({
  id: '/spoude',
  path: '/spoude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsIdRoute = AuthenticatedSetsIdRouteImport.update({
  id: '/sets/$id',
  path: '/sets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spoude': typeof AuthenticatedSpoudeRoute
  '/spoude-library': typeof AuthenticatedSpoudeLibraryRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
  '/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spoude': typeof AuthenticatedSpoudeRoute
  '/spoude-library': typeof AuthenticatedSpoudeLibraryRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
  '/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acceptable-use': typeof AcceptableUseRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spoude': typeof AuthenticatedSpoudeRoute
  '/_authenticated/spoude-library': typeof AuthenticatedSpoudeLibraryRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/api/teach': typeof ApiTeachRoute
  '/_authenticated/sets/$id': typeof AuthenticatedSetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/billing'
    | '/exams'
    | '/help'
    | '/library'
    | '/profile'
    | '/settings'
    | '/spoude'
    | '/spoude-library'
    | '/study'
    | '/api/teach'
    | '/sets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/billing'
    | '/exams'
    | '/help'
    | '/library'
    | '/profile'
    | '/settings'
    | '/spoude'
    | '/spoude-library'
    | '/study'
    | '/api/teach'
    | '/sets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceptable-use'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/exams'
    | '/_authenticated/help'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/spoude'
    | '/_authenticated/spoude-library'
    | '/_authenticated/study'
    | '/api/teach'
    | '/_authenticated/sets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptableUseRoute: typeof AcceptableUseRoute
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiTeachRoute: typeof ApiTeachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teach': {
      id: '/api/teach'
      path: '/api/teach'
      fullPath: '/api/teach'
      preLoaderRoute: typeof ApiTeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spoude-library': {
      id: '/_authenticated/spoude-library'
      path: '/spoude-library'
      fullPath: '/spoude-library'
      preLoaderRoute: typeof AuthenticatedSpoudeLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spoude': {
      id: '/_authenticated/spoude'
      path: '/spoude'
      fullPath: '/spoude'
      preLoaderRoute: typeof AuthenticatedSpoudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sets/$id': {
      id: '/_authenticated/sets/$id'
      path: '/sets/$id'
      fullPath: '/sets/$id'
      preLoaderRoute: typeof AuthenticatedSetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpoudeRoute: typeof AuthenticatedSpoudeRoute
  AuthenticatedSpoudeLibraryRoute: typeof AuthenticatedSpoudeLibraryRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedSetsIdRoute: typeof AuthenticatedSetsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpoudeRoute: AuthenticatedSpoudeRoute,
  AuthenticatedSpoudeLibraryRoute: AuthenticatedSpoudeLibraryRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedSetsIdRoute: AuthenticatedSetsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptableUseRoute: AcceptableUseRoute,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiTeachRoute: ApiTeachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
